// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCOvtQTaTcI-3hPw97wLeH8ov3GPkm8--Q',
    appId: '1:246765796090:web:0fd00e9ebb471a5e6ba743',
    messagingSenderId: '246765796090',
    projectId: 'it-shop-c9a79',
    authDomain: 'it-shop-c9a79.firebaseapp.com',
    storageBucket: 'it-shop-c9a79.appspot.com',
    measurementId: 'G-23L555J93E',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAyu0A1a8_AZ2Dq72UK7tjfXj0LnfSuFvo',
    appId: '1:246765796090:android:4b016c5ac5cb7fed6ba743',
    messagingSenderId: '246765796090',
    projectId: 'it-shop-c9a79',
    storageBucket: 'it-shop-c9a79.appspot.com',
  );
}
